/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminNavBar: typeof import('./src/components/AdminNavBar.vue')['default']
    ButtonThema: typeof import('./src/components/ButtonThema.vue')['default']
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ListagemProdutos: typeof import('./src/components/ListagemProdutos.vue')['default']
    ListProdutos: typeof import('./src/components/PainelAdministrativo/ListProdutos.vue')['default']
    MenuCategorias: typeof import('./src/components/MenuCategorias.vue')['default']
    Navbar: typeof import('./src/components/PainelAdministrativo/Navbar.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadImage: typeof import('./src/components/UploadImage.vue')['default']
  }
}
