/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonThema: typeof import('./src/components/ButtonThema.vue')['default']
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    DragDrop: typeof import('./src/components/DragDrop.vue')['default']
    ListagemProdutos: typeof import('./src/components/ListagemProdutos.vue')['default']
    MenuCategorias: typeof import('./src/components/MenuCategorias.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadImage: typeof import('./src/components/UploadImage.vue')['default']
  }
}
