/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/categorias/': RouteRecordInfo<'/categorias/', '/categorias', Record<never, never>, Record<never, never>>,
    '/configuracoes/': RouteRecordInfo<'/configuracoes/', '/configuracoes', Record<never, never>, Record<never, never>>,
    '/error-404/': RouteRecordInfo<'/error-404/', '/error-404', Record<never, never>, Record<never, never>>,
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
    '/listprodutos/': RouteRecordInfo<'/listprodutos/', '/listprodutos', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/produtos/[id]': RouteRecordInfo<'/produtos/[id]', '/produtos/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
